import React, { PropsWithChildren } from 'react';
import Head from 'next/head';

import { NextPage } from 'next';

import SideBar from '@/common/components/sideBar/sideBar';

import { Header } from '../header';

// type Props = {
//     children: ReactNode;
// };

export const Layout: NextPage<PropsWithChildren> = ({ children }) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>My profile</title>
      </Head>
      <Header/>
      <div style={{ display: 'flex' }}>
        <SideBar/>
        <main>{children}</main>
      </div>

    </>
  );
};
