import { PropsWithChildren, ReactElement, ReactNode } from 'react'

import { NextPage } from 'next'
import Head from 'next/head'

import { Header } from '@/common/components/header'

const LayoutWithHeader: NextPage<PropsWithChildren> = ({ children }: { children?: ReactNode }) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>My profile</title>
      </Head>
      <Header />
      <main>{children}</main>
    </>
  )
}

const LayoutHeader: NextPage<PropsWithChildren> = ({ children }: { children?: ReactNode }) => {
  return <LayoutWithHeader>{children}</LayoutWithHeader>
}

export function getLayoutHeader(page: ReactElement): JSX.Element {
  return <LayoutHeader>{page}</LayoutHeader>
}

export default LayoutHeader
