import Head from 'next/head'

import SharedHeader from '@/shared/header/SharedHeader';
import SideBar from '@/shared/sideBar/sideBar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>
      <main>
        <SharedHeader/>
        <SideBar/>
      </main>
    </>
  )
}
