import { PropsWithChildren, ReactElement, ReactNode } from 'react'

import { NextPage } from 'next'
import Head from 'next/head'

import { Header } from '../../header'

import { Container } from '@/common/components/container'
import SideBar from '@/common/components/sideBar/sideBar'

export const LayoutWithSideBar: NextPage<PropsWithChildren> = ({
  children,
}: {
  children?: ReactNode
}) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>My profile</title>
      </Head>
      <Header />
      <Container type="shared" style={{ display: 'flex' }}>
        <SideBar />
        <main>{children}</main>
      </Container>
    </>
  )
}

const LayoutSideBar: NextPage<PropsWithChildren> = ({ children }: { children?: ReactNode }) => {
  return <LayoutWithSideBar>{children}</LayoutWithSideBar>
}

export function getLayoutSideBar(page: ReactElement): JSX.Element {
  return <LayoutSideBar>{page}</LayoutSideBar>
}
