import React, { PropsWithChildren, ReactElement } from 'react';
import Head from 'next/head';
import { NextPage } from 'next';

import SideBar from '@/common/components/sideBar/sideBar';
import { Container } from '@/common/components/container';

import { Header } from '../../header';

export const LayoutWithSideBar: NextPage<PropsWithChildren> = ({ children }) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>My profile</title>
      </Head>
      <Header/>
      <Container type={'shared'} style={{ display: 'flex' }}>
        <SideBar/>
        <main>{children}</main>
      </Container>
    </>
  );
};

const LayoutSideBar: NextPage<PropsWithChildren> = ({ children }) => {
  return (
    <LayoutWithSideBar>{children}</LayoutWithSideBar>
  );
};

export function getLayoutSideBar(page: ReactElement) {
  return <LayoutSideBar>{page}</LayoutSideBar>
}
