import React, { FC, ReactNode, useState } from 'react';
import Head from 'next/head';

import { Header } from '@/shared/header';
import LogOutButton from '@/features/auth/ui/logOut/logOutButton';
import ModalWindow from '@/shared/modalWindow/modalWindow';
import { Button } from '@/shared/button/Button';
import { selectEmail, selectIsAuth, useAuthStore } from '@/features/auth/store';
import ModalForLogOut from '@/features/auth/ui/logOut/modalForLogOut';

type Props = {
    children: ReactNode
}
export const Layout: FC<Props> = ({ children }) => {

  const isAuth = useAuthStore(selectIsAuth)

  const [isActiveModal, setIsActiveModal] = useState(false)

  const logOutButtonHandler = (value: boolean) => setIsActiveModal(value)

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>
      <Header>{isAuth && <LogOutButton callBack={logOutButtonHandler}/>}</Header>
      <ModalForLogOut isActiveModal={isActiveModal} setIsActiveModal={setIsActiveModal}/>
      <main>
        {children}
      </main>
    </>
  );
};
