import React, { FC, ReactNode } from 'react';
import Head from 'next/head';

type Props = {
    children: ReactNode
}
export const Layout: FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>
      {/*<Header><LogOutButton/></Header>*/}

      <main>
        {children}
      </main>
    </>
  );
};
