import React, { FC, ReactNode, useState } from 'react';
import Head from 'next/head';

import { Header } from '@/shared/header';
import ModalForLogOut from '@/features/auth/ui/logOut/modalForLogOut';
import { selectIsAuth, useAuthStore } from '@/features/auth/store';

type Props = {
    children: ReactNode
}
export const Layout: FC<Props> = ({ children }) => {

  // const isAuth = useAuthStore(selectIsAuth)

  const [isActiveModal, setIsActiveModal] = useState(false)

  // const logOutButtonHandler = (value: boolean) => setIsActiveModal(value)

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>
      <Header></Header>
      <ModalForLogOut isActiveModal={isActiveModal} setIsActiveModal={setIsActiveModal}/>
      <main>
        {children}
      </main>
    </>
  );
};
